-- 코드를 입력하세요

WITH RECURSIVE TIME AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 
      FROM TIME 
     WHERE HOUR < 23
)

SELECT T.HOUR, 
       IF(A.COUNT IS NULL, 0, A.COUNT) AS 'COUNT'
  FROM (
    SELECT HOUR(DATETIME) AS 'HOUR', 
           COUNT(*) AS 'COUNT'
      FROM ANIMAL_OUTS 
     GROUP BY HOUR
) A
 RIGHT JOIN TIME T ON A.HOUR = T.HOUR;